version: '3.5'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /opt/docker/mysql/conf:/etc/mysql/conf.d
      - /opt/docker/mysql/logs:/logs
      - /opt/docker/mysql/data:/var/lib/mysql
      - /opt/myblog-api/myblog.sql:/root/myblog.sql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: [ "redis-server", "--requirepass", "admin123"]

  myblog_api:
    image: myblog_api:v6
    container_name: myblog_api
    ports:
      - "8000:8000"
    restart: always
    links:
      - mysql
      - redis

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "2000:80"
    volumes:
      - /opt/myblog-api/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - myblog_api

  web-pc:
    image: myblog_pc:v4
    container_name: web-pc
    ports:
      - "80:80"
    restart: always
    depends_on:
      - nginx

networks:
  web-api:
    ipam:
      config:
        - subnet: 192.168.220.0/24
