version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./logs:/logs
      - ./data:/var/lib/mysql
      - /opt/myblog-api:/root/myblog-api
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    restart: always